### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Charlesetc** [vitvad/Access-Control-Allow-Origin#20]
Is there any chance you can add some open-source compliant license to this repo?

Great extension, by the way!

**Comment by vitvad** [comment]
@Charlesetc, what the main concern of this ? 
Maybe will, but never thought about this before.

**Comment by Charlesetc** [comment]
We'll it'd be nice to be able to fork it and play with it, but that's not technically allowed without a license.

**Comment by vitvad** [comment]
added MIT

**Comment by hadrien-toma** [comment]
May I suggest that you add a LICENSE file about this great choice (MIT) in the repository? Thank you for releasing Open Source Softwares!
