### ISSUE TITLE
Changes in "intercepted URL or URL pattern" doesn t work

### ISSUE THREAD

**Issue by raphg51** [vitvad/Access-Control-Allow-Origin#22]
Hie, and thx for you r usefull application.

I ve an issue when i add a new url pattern, my new entry is just ignored and the old one (by default) is keeped.

Can you fix this please, it would be usefull?

Thx

**Comment by cfjedimaster** [comment]
Same here.

**Comment by donortega** [comment]
Also not working for me either.

**Comment by herkulano** [comment]
+1

**Comment by hatelove85911** [comment]
+1, I don't want cors to be enabled for all urls, so I add my own url pattern, but after the popup window of this plugin is closed and open again, the custom urls I add is lost, only the default url pattern is still there. that's: *://*/*

**Comment by zamf** [comment]
Same here.

**Comment by vrde** [comment]
workaround: open `background.js` from the extension panel, open the console and type `chrome.storage.local.set({'urls': ["http://mydomain.com/*";]})`.

**Comment by raphg51** [comment]
Thank you!


Envoyé depuis mon Samsung Galaxy S 4 d’Orange

<div>-------- Message d'origine --------</div><div>De : Alberto Granzotto <notifications@github.com> </div><div>Date :08/06/2015  10:08  (GMT+01:00) </div><div>A : vitvad/Access-Control-Allow-Origin <Access-Control-Allow-Origin@noreply.github.com> </div><div>Cc : raphg51 <raph.g@neuf.fr> </div><div>Objet : Re: [Access-Control-Allow-Origin] Changes in "intercepted URL or
  URL pattern" doesn t work (#22) </div><div>
</div>workaround: open background.js from the extension panel, open the console and type chrome.storage.local.set({'urls': ["http://mydomain.com/*";]}).

**Comment by cfjedimaster** [comment]
Tempted to fork the project and build in a proper fix.

**Comment by herkulano** [comment]
Please do. :smiley:

**Comment by fgrs** [comment]
doesn't work for me either

**Comment by pasqLisena** [comment]
I have just proposed a [fix](https://github.com/vitvad/Access-Control-Allow-Origin/pull/24).
I hope that devs accept my pull request :smiley:

**Comment by vitvad** [comment]
just updated extension in chrome store 
should be ok now

**Comment by pasqLisena** [comment]
Successfully tested!
Tank you :smile:
