### ISSUE TITLE
Pattern matching not working as expected

### ISSUE THREAD

**Issue by raimondi1337** [vitvad/Access-Control-Allow-Origin#55]
`*://*/*` fixes the errors I'm having while running applications locally on `http:/localhost:3003/`, but it causes problems with other sites (github) so I'd like to limit it to localhost, but I can't get any pattern other than the above working.

None of these fix my issues on localhost, what gives?

`*://localhost/*`
`*://localhost:*/*`
`*://localhost:3003/*`
`http://localhost/*`
`localhost/*`
`http://127.0.0.1/*`
`*://127.0.0.1/*`
`*://127.0.0.1:3003/*`

**Comment by raimondi1337** [comment]
I was going in the wrong direction lololol

**Comment by ryuujo** [comment]
So how did you fix it?
