### ISSUE TITLE
Not on Webstore anymore

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [vitvad/Access-Control-Allow-Origin#59]
https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi is not valid anymore.

can you provide extension here?

**Comment by vitvad** [comment]
google unpublished extension - you can take it from dev branch and use in developer mode 
I'm not going to do anything here and publish it back in nearest times.
besides I saw someone posted already extension similar to mine
